# Generated by Django 2.2.2 on 2020-02-08 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainaccepted', '0003_auto_20200207_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='submitEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('organisation', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Submit Events',
            },
        ),
    ]
